name = "paper-talk"
main = "src/worker.js"
compatibility_date = "2025-01-01"

[vars]
CLOUDFLARE_AI_MODEL = "@cf/openai/gpt-oss-120b"

[assets]
directory = "./public"

[[d1_databases]]
binding = "DB"
database_name = "paper-talk-db"
database_id = "5b33c4d2-9d1d-47f0-993f-a694c2b05d8a"

[ai]
binding = "AI"

[[vectorize]]
binding = "VECTORIZE"
index_name = "paper-talk-research"
