name = "paper-talk"
main = "src/index.js"
compatibility_date = "2025-01-01"

[placement]
region = "aws:ap-northeast-1"

[[d1_databases]]
binding = "DB"
database_name = "paper-talk-db"
database_id = "5b33c4d2-9d1d-47f0-993f-a694c2b05d8a"

[assets]
directory = "./public"

[ai]
binding = "AI"

[[vectorize]]
binding = "VECTORIZE"
index_name = "paper-talk-research"
